-- DELETE FROM NOTES;
-- DELETE FROM CATEGORIES;
-- DELETE FROM USERS;
-- INSERT INTO CATEGORIES(category_id,category_name)
-- VALUES (0,'gotowanie'),(1,'ważne'),(2,'przypominajki');
-- INSERT INTO USERS(name,surname,login,password,age,role_id)
-- values ('admin','admin','admin','$2a$12$ZHKaoMnBKYxqG.adDiyXBet7PaHKVHo4DjV3WC37fxEzWd5iwENiW',30,1);
-- INSERT INTO NOTES(title,content,link,add_date,reminder_date,category_id,user_id)
-- VALUES('przepis','Żabie udka w sosie','www.wp.pl','2023-06-05','2023-06-07',(select CATEGORY_ID FROM CATEGORIES WHERE CATEGORIES.CATEGORY_NAME='gotowanie'),(select user_id from USERS where users.login='user1')),
-- ('abrakdabra','czarna magia','www.onet.pl','2023-06-04','2023-06-06',(select CATEGORY_ID FROM CATEGORIES WHERE CATEGORIES.CATEGORY_NAME='ważne'),(select user_id from USERS where users.login='user1'));
-- INSERT INTO USERS(name,surname,login,password,age,role_id)
-- values ('user3','user3','user3','user3',30,3);
SELECT * from users;